/**
 * Shoshan Varod — Données Mock
 * Données réalistes pour le développement avant connexion WordPress
 */

import type { Product, Category, Brand } from './types';

// ----- Marques -----

export const brands: Brand[] = [
  { name: 'Sandro', slug: 'sandro' },
  { name: 'Maje', slug: 'maje' },
  { name: 'Isabel Marant', slug: 'isabel-marant' },
  { name: 'A.P.C.', slug: 'apc' },
  { name: 'Zadig & Voltaire', slug: 'zadig-voltaire' },
  { name: 'Claudie Pierlot', slug: 'claudie-pierlot' },
  { name: 'Ba&sh', slug: 'bash' },
  { name: 'Acne Studios', slug: 'acne-studios' },
  { name: 'American Vintage', slug: 'american-vintage' },
  { name: 'The Kooples', slug: 'the-kooples' },
  { name: 'Kenzo', slug: 'kenzo' },
  { name: 'Ganni', slug: 'ganni' },
  { name: 'Totême', slug: 'toteme' },
  { name: 'Jacquemus', slug: 'jacquemus' },
  { name: 'Ami Paris', slug: 'ami-paris' },
];

// ----- Catégories -----

export const categories: Category[] = [
  {
    id: 1,
    slug: 'robes',
    name: 'Robes',
    description: 'Robes de créateurs, du cocktail au quotidien raffiné.',
    image: '/images/categories/robes.jpg',
    count: 4,
  },
  {
    id: 2,
    slug: 'manteaux-vestes',
    name: 'Manteaux & Vestes',
    description: 'Pièces de caractère pour sublimer vos silhouettes.',
    image: '/images/categories/manteaux.jpg',
    count: 3,
  },
  {
    id: 3,
    slug: 'sacs',
    name: 'Sacs',
    description: 'Sacs à main et accessoires de maisons prestigieuses.',
    image: '/images/categories/sacs.jpg',
    count: 3,
  },
  {
    id: 4,
    slug: 'pulls-mailles',
    name: 'Pulls & Mailles',
    description: 'Mailles de qualité, cachemire et laine mérinos.',
    image: '/images/categories/pulls.jpg',
    count: 3,
  },
  {
    id: 5,
    slug: 'pantalons',
    name: 'Pantalons',
    description: 'Coupes impeccables pour un style assuré.',
    image: '/images/categories/pantalons.jpg',
    count: 2,
  },
  {
    id: 6,
    slug: 'accessoires',
    name: 'Accessoires',
    description: 'Ceintures, foulards et bijoux pour parfaire votre allure.',
    image: '/images/categories/accessoires.jpg',
    count: 3,
  },
];

// ----- Produits -----

export const products: Product[] = [
  // --- ROBES ---
  {
    id: 1,
    slug: 'robe-midi-sandro-fleurie',
    name: 'Robe Midi Fleurie',
    brand: 'Sandro',
    category: 'Robes',
    categorySlug: 'robes',
    price: 89,
    originalPrice: 295,
    size: '38',
    color: 'Noir & Rose',
    material: 'Polyester, Soie',
    condition: 'Excellent',
    description: 'Sublime robe midi Sandro à imprimé floral délicat. Coupe fluide et flatteuse avec une ceinture à nouer à la taille. Détails en dentelle sur les épaules. Cette pièce incarne l\'élégance parisienne avec son mélange de romantisme et de modernité. Portée seulement deux fois, elle est en état impeccable.',
    shortDescription: 'Robe midi fluide à imprimé floral, ceinture à nouer.',
    images: ['/images/products/robe-sandro-1.jpg', '/images/products/robe-sandro-2.jpg'],
    isFeatured: true,
    isNew: true,
    isSold: false,
    tags: ['fleurie', 'midi', 'été'],
    createdAt: '2025-04-15',
  },
  {
    id: 2,
    slug: 'robe-maje-noire-dentelle',
    name: 'Robe Noire Dentelle',
    brand: 'Maje',
    category: 'Robes',
    categorySlug: 'robes',
    price: 75,
    originalPrice: 325,
    size: '36',
    color: 'Noir',
    material: 'Polyester, Dentelle',
    condition: 'Très bon',
    description: 'Petite robe noire Maje en dentelle fine avec doublure en soie. Coupe ajustée, longueur au-dessus du genou. Fermeture zip invisible au dos. Un basique intemporel rehaussé par les détails de dentelle qui lui confèrent une touche de sophistication.',
    shortDescription: 'Petite robe noire en dentelle fine, coupe ajustée.',
    images: ['/images/products/robe-maje-1.jpg', '/images/products/robe-maje-2.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['dentelle', 'soirée', 'intemporel'],
    createdAt: '2025-03-20',
  },
  {
    id: 3,
    slug: 'robe-bash-cache-coeur',
    name: 'Robe Cache-Cœur Satinée',
    brand: 'Ba&sh',
    category: 'Robes',
    categorySlug: 'robes',
    price: 65,
    originalPrice: 245,
    size: '40',
    color: 'Bordeaux',
    material: 'Viscose, Satin',
    condition: 'Bon',
    description: 'Robe cache-cœur Ba&sh en satin fluide couleur bordeaux. Manches trois-quarts avec détails froncés. Ceinture intégrée. Parfaite pour une soirée ou un dîner élégant.',
    shortDescription: 'Robe cache-cœur en satin bordeaux, manches 3/4.',
    images: ['/images/products/robe-bash-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['satin', 'bordeaux', 'soirée'],
    createdAt: '2025-02-10',
  },
  {
    id: 4,
    slug: 'robe-ganni-imprimee',
    name: 'Robe Chemise Imprimée',
    brand: 'Ganni',
    category: 'Robes',
    categorySlug: 'robes',
    price: 95,
    originalPrice: 375,
    size: '38',
    color: 'Multicolore',
    material: 'Coton Organique',
    condition: 'Excellent',
    description: 'Robe chemise Ganni en coton biologique avec imprimé géométrique signature. Coupe oversize décontractée, boutons nacrés sur le devant. Col pointu et poches latérales. Un mélange parfait de décontraction scandinave et de chic responsable.',
    shortDescription: 'Robe chemise oversize à imprimé géométrique.',
    images: ['/images/products/robe-ganni-1.jpg'],
    isFeatured: true,
    isNew: true,
    isSold: false,
    tags: ['imprimé', 'chemise', 'oversize', 'éco-responsable'],
    createdAt: '2025-04-18',
  },

  // --- MANTEAUX & VESTES ---
  {
    id: 5,
    slug: 'manteau-acne-studios-laine',
    name: 'Manteau Oversize Laine',
    brand: 'Acne Studios',
    category: 'Manteaux & Vestes',
    categorySlug: 'manteaux-vestes',
    price: 195,
    originalPrice: 850,
    size: '40',
    color: 'Camel',
    material: 'Laine Vierge, Cachemire',
    condition: 'Excellent',
    description: 'Manteau oversize Acne Studios en laine mélangée cachemire. Coupe droite tombante, épaules descendues. Double boutonnage avec boutons gainés. Poches plaquées. Une pièce d\'investissement par excellence, qui traverse les saisons et les tendances avec une grâce inégalée.',
    shortDescription: 'Manteau oversize en laine et cachemire, double boutonnage.',
    images: ['/images/products/manteau-acne-1.jpg', '/images/products/manteau-acne-2.jpg'],
    isFeatured: true,
    isNew: false,
    isSold: false,
    tags: ['laine', 'camel', 'oversize', 'hiver'],
    createdAt: '2025-01-15',
  },
  {
    id: 6,
    slug: 'veste-blazer-the-kooples',
    name: 'Blazer à Revers Satin',
    brand: 'The Kooples',
    category: 'Manteaux & Vestes',
    categorySlug: 'manteaux-vestes',
    price: 110,
    originalPrice: 425,
    size: '38',
    color: 'Noir',
    material: 'Laine, Satin',
    condition: 'Très bon',
    description: 'Blazer The Kooples à revers en satin, inspiration smoking. Coupe cintrée, fermeture par un bouton. Poches passepoilées. Doublure imprimée. L\'alliance parfaite entre masculin et féminin, idéal pour un look rock-chic.',
    shortDescription: 'Blazer smoking à revers satin, coupe cintrée.',
    images: ['/images/products/blazer-kooples-1.jpg'],
    isFeatured: false,
    isNew: true,
    isSold: false,
    tags: ['blazer', 'smoking', 'rock-chic'],
    createdAt: '2025-04-10',
  },
  {
    id: 7,
    slug: 'veste-isabel-marant-daim',
    name: 'Veste en Daim Frangée',
    brand: 'Isabel Marant',
    category: 'Manteaux & Vestes',
    categorySlug: 'manteaux-vestes',
    price: 180,
    originalPrice: 790,
    size: '36',
    color: 'Cognac',
    material: 'Daim de Chèvre',
    condition: 'Très bon',
    description: 'Veste en daim Isabel Marant avec franges sur le devant et dans le dos. Coupe courte ajustée. Fermeture par boutons-pression. Poches à rabat. Une pièce iconique qui incarne l\'esprit bohème-chic de la maison.',
    shortDescription: 'Veste en daim cognac avec franges, coupe courte.',
    images: ['/images/products/veste-marant-1.jpg'],
    isFeatured: true,
    isNew: false,
    isSold: false,
    tags: ['daim', 'franges', 'bohème'],
    createdAt: '2025-02-28',
  },

  // --- SACS ---
  {
    id: 8,
    slug: 'sac-apc-demi-lune',
    name: 'Sac Demi-Lune',
    brand: 'A.P.C.',
    category: 'Sacs',
    categorySlug: 'sacs',
    price: 145,
    originalPrice: 460,
    size: 'Unique',
    color: 'Noir',
    material: 'Cuir de Veau',
    condition: 'Excellent',
    description: 'Le mythique sac Demi-Lune d\'A.P.C. en cuir lisse noir. Bandoulière ajustable, fermeture zip. Doublure en coton. Un classique intemporel du vestiaire parisien minimaliste. Cuir patiné avec grâce, aucune usure visible.',
    shortDescription: 'Sac bandoulière iconique en cuir lisse noir.',
    images: ['/images/products/sac-apc-1.jpg', '/images/products/sac-apc-2.jpg'],
    isFeatured: true,
    isNew: false,
    isSold: false,
    tags: ['cuir', 'bandoulière', 'minimaliste'],
    createdAt: '2025-03-05',
  },
  {
    id: 9,
    slug: 'sac-zadig-rock-nano',
    name: 'Rock Nano Suédé',
    brand: 'Zadig & Voltaire',
    category: 'Sacs',
    categorySlug: 'sacs',
    price: 120,
    originalPrice: 398,
    size: 'Unique',
    color: 'Kaki',
    material: 'Cuir Suédé',
    condition: 'Très bon',
    description: 'Sac Rock Nano Zadig & Voltaire en cuir suédé kaki. Chaîne argentée et bandoulière en cuir. Fermoir signature en métal. Intérieur en coton avec une poche. Le compagnon parfait pour un look décontracté-chic.',
    shortDescription: 'Petit sac à chaîne en suédé kaki, fermoir métal.',
    images: ['/images/products/sac-zadig-1.jpg'],
    isFeatured: false,
    isNew: true,
    isSold: false,
    tags: ['suédé', 'chaîne', 'rock'],
    createdAt: '2025-04-12',
  },
  {
    id: 10,
    slug: 'sac-claudie-pierlot-anouck',
    name: 'Sac Anouck Cuir Grainé',
    brand: 'Claudie Pierlot',
    category: 'Sacs',
    categorySlug: 'sacs',
    price: 95,
    originalPrice: 295,
    size: 'Unique',
    color: 'Caramel',
    material: 'Cuir Grainé',
    condition: 'Bon',
    description: 'Sac Anouck Claudie Pierlot en cuir grainé caramel. Rabat avec fermoir doré. Bandoulière amovible et ajustable. Compartiment principal avec poche intérieure zippée. Élégance discrète pour le quotidien.',
    shortDescription: 'Sac à rabat en cuir grainé caramel, fermoir doré.',
    images: ['/images/products/sac-claudie-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['cuir', 'rabat', 'quotidien'],
    createdAt: '2025-01-20',
  },

  // --- PULLS & MAILLES ---
  {
    id: 11,
    slug: 'pull-toteme-cachemire',
    name: 'Pull Col Roulé Cachemire',
    brand: 'Totême',
    category: 'Pulls & Mailles',
    categorySlug: 'pulls-mailles',
    price: 135,
    originalPrice: 490,
    size: 'M',
    color: 'Crème',
    material: '100% Cachemire',
    condition: 'Excellent',
    description: 'Pull col roulé Totême en pur cachemire crème. Maille fine et douce, coupe légèrement oversize. Côtes aux poignets et à l\'ourlet. L\'incarnation du luxe discret à la scandinave. Pièce de garde-robe essentielle.',
    shortDescription: 'Col roulé en pur cachemire, coupe oversize.',
    images: ['/images/products/pull-toteme-1.jpg'],
    isFeatured: true,
    isNew: false,
    isSold: false,
    tags: ['cachemire', 'col roulé', 'minimaliste'],
    createdAt: '2025-03-01',
  },
  {
    id: 12,
    slug: 'pull-ami-paris-coeur',
    name: 'Pull Ami de Cœur',
    brand: 'Ami Paris',
    category: 'Pulls & Mailles',
    categorySlug: 'pulls-mailles',
    price: 85,
    originalPrice: 280,
    size: 'L',
    color: 'Marine',
    material: 'Laine Mérinos',
    condition: 'Très bon',
    description: 'Pull Ami Paris en laine mérinos marine avec le broderie « Ami de Cœur » emblématique. Col rond, coupe droite. Côtes épaisses. Pièce signature d\'Alexandre Mattiussi, entre streetwear et élégance française.',
    shortDescription: 'Pull en laine mérinos avec broderie cœur signature.',
    images: ['/images/products/pull-ami-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['laine', 'broderie', 'signature'],
    createdAt: '2025-02-15',
  },
  {
    id: 13,
    slug: 'cardigan-sandro-mohair',
    name: 'Cardigan Mohair Bouclé',
    brand: 'Sandro',
    category: 'Pulls & Mailles',
    categorySlug: 'pulls-mailles',
    price: 70,
    originalPrice: 265,
    size: '38',
    color: 'Rose Poudré',
    material: 'Mohair, Laine',
    condition: 'Bon',
    description: 'Cardigan Sandro en mohair bouclé rose poudré. Boutons bijoux dorés. Col en V profond. Texture duveteuse et légère. Une pièce cocooning qui ajoute une touche de douceur à n\'importe quel look.',
    shortDescription: 'Cardigan mohair rose poudré, boutons bijoux dorés.',
    images: ['/images/products/cardigan-sandro-1.jpg'],
    isFeatured: false,
    isNew: true,
    isSold: false,
    tags: ['mohair', 'rose', 'cardigan'],
    createdAt: '2025-04-14',
  },

  // --- PANTALONS ---
  {
    id: 14,
    slug: 'pantalon-jacquemus-lin',
    name: 'Pantalon Large Lin',
    brand: 'Jacquemus',
    category: 'Pantalons',
    categorySlug: 'pantalons',
    price: 105,
    originalPrice: 390,
    size: '40',
    color: 'Écru',
    material: '100% Lin',
    condition: 'Excellent',
    description: 'Pantalon Jacquemus en lin écru, coupe large et haute. Taille élastiquée au dos avec ceinture à nouer. Plis marqués sur le devant. L\'esprit sud de la France dans un pantalon : décontracté, solaire et terriblement chic.',
    shortDescription: 'Pantalon large en lin écru, taille haute à nouer.',
    images: ['/images/products/pantalon-jacquemus-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['lin', 'large', 'été'],
    createdAt: '2025-03-18',
  },
  {
    id: 15,
    slug: 'jean-acne-studios-droit',
    name: 'Jean Droit Taille Haute',
    brand: 'Acne Studios',
    category: 'Pantalons',
    categorySlug: 'pantalons',
    price: 75,
    originalPrice: 280,
    size: '38',
    color: 'Bleu Délavé',
    material: 'Denim Coton',
    condition: 'Très bon',
    description: 'Jean Acne Studios coupe droite taille haute en denim délavé. Cinq poches, fermeture à boutons. Patch logo au dos. Le jean parfait : coupe flatteuse, denim de qualité, délavage subtil.',
    shortDescription: 'Jean droit taille haute en denim délavé.',
    images: ['/images/products/jean-acne-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['denim', 'droit', 'taille haute'],
    createdAt: '2025-02-05',
  },

  // --- ACCESSOIRES ---
  {
    id: 16,
    slug: 'ceinture-kenzo-cuir',
    name: 'Ceinture Tigre Cuir',
    brand: 'Kenzo',
    category: 'Accessoires',
    categorySlug: 'accessoires',
    price: 55,
    originalPrice: 195,
    size: '80',
    color: 'Noir',
    material: 'Cuir de Veau',
    condition: 'Excellent',
    description: 'Ceinture Kenzo en cuir lisse noir avec boucle tigre en métal argenté. Largeur 3cm. Passant en cuir. Pièce iconique de la maison, parfaite pour structurer une silhouette avec caractère.',
    shortDescription: 'Ceinture cuir noir, boucle tigre métal argenté.',
    images: ['/images/products/ceinture-kenzo-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['cuir', 'ceinture', 'signature'],
    createdAt: '2025-03-25',
  },
  {
    id: 17,
    slug: 'foulard-maje-soie',
    name: 'Foulard Carré Soie',
    brand: 'Maje',
    category: 'Accessoires',
    categorySlug: 'accessoires',
    price: 45,
    originalPrice: 155,
    size: '90x90cm',
    color: 'Imprimé',
    material: '100% Soie',
    condition: 'Excellent',
    description: 'Foulard carré Maje en soie naturelle avec imprimé chaînes dorées sur fond marine. Ourlet roulotté main. Polyvalent : autour du cou, dans les cheveux ou sur un sac. Livré dans sa pochette d\'origine.',
    shortDescription: 'Carré de soie imprimé chaînes, ourlet roulotté.',
    images: ['/images/products/foulard-maje-1.jpg'],
    isFeatured: false,
    isNew: true,
    isSold: false,
    tags: ['soie', 'foulard', 'imprimé'],
    createdAt: '2025-04-16',
  },
  {
    id: 18,
    slug: 'echarpe-american-vintage-laine',
    name: 'Écharpe Oversize Laine',
    brand: 'American Vintage',
    category: 'Accessoires',
    categorySlug: 'accessoires',
    price: 35,
    originalPrice: 95,
    size: 'Unique',
    color: 'Gris Chiné',
    material: 'Laine, Alpaga',
    condition: 'Très bon',
    description: 'Grande écharpe American Vintage en laine et alpaga gris chiné. Texture douce et enveloppante. Franges aux extrémités. Dimensions généreuses (200x70cm). L\'accessoire cocooning indispensable pour l\'hiver.',
    shortDescription: 'Grande écharpe en laine et alpaga, franges.',
    images: ['/images/products/echarpe-amvintage-1.jpg'],
    isFeatured: false,
    isNew: false,
    isSold: false,
    tags: ['laine', 'alpaga', 'hiver', 'oversize'],
    createdAt: '2025-01-30',
  },
];

// ----- Helper Functions -----

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(p => p.categorySlug === categorySlug && !p.isSold);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.isFeatured && !p.isSold);
}

export function getNewProducts(): Product[] {
  return products.filter(p => p.isNew && !p.isSold);
}

export function getRelatedProducts(currentProduct: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== currentProduct.id && p.categorySlug === currentProduct.categorySlug && !p.isSold)
    .slice(0, limit);
}

export function getAllAvailableProducts(): Product[] {
  return products.filter(p => !p.isSold);
}

export function getDiscountPercentage(product: Product): number {
  return Math.round(((product.originalPrice - product.price) / product.originalPrice) * 100);
}
